[tool.poetry]
name = "opthub-client"
version = "0.1.0"
description = ""
authors = ["tkumamoto <kumamoto.t.ab@m.titech.ac.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
inquirerpy = "^0.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

