[tool.poetry]
name = "opthub_client"
version = "0.1.0"
description = ""
authors = ["tkumamoto <kumamoto.t.ab@m.titech.ac.jp>"]
readme = "README.md"

[[tool.poetry.packages]]
include = "src"

[tool.ruff]
target-version = "py312"
line-length = 120
select = ["ALL"]
ignore = [
    "ANN101", # 引数selfには型ヒントは付けない
    "D100",  # モジュールのdocstringは書かない
    "D104", # モジュールのdocstringは書かない
    "D4", # docstringのフォーマットの制限を緩くする
    "RET504", # 関数の返り値の前の代入を許可
    "T201", # print関数は使用可能に
    "FBT001", # bool型の位置引数を許可
    "ARG001", # 使われていない変数の許可
    "TD002", # Todoでアサインしなくても良いように
    "TD003", # TodoにIssueを紐付けなくても良いように
]

[tool.poetry.dependencies]
python = "3.12.1"
click = "^8.1.7"
prompt-toolkit = "^3.0.43"
inquirerpy = "^0.3.4"
gql = "^3.5.0"
aiohttp = "^3.9.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.3"
mypy = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
opt = "opt:opt"
