[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["tkumamoto <kumamoto.t.ab@m.titech.ac.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
prompt-toolkit = "^3.0.43"
inquirerpy = "^0.3.4"
gql = "^3.5.0"
aiohttp = "^3.9.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
opt = "src.opt:opt"