name: Release

on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
    - id: release-please
      uses: googleapis/release-please-action@v4
      with:
        release-type: python
  pypi:
    needs: github-release
    if: ${{ needs.github-release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for accurate versioning
    - uses: ./.github/workflows/actions/poetry_publish
      with:
        testpypi: true
        testpypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
        pypi: true
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
